# Toggle all messages globally
enable-messages: true

# Chance in percent to replace block drops with random drops
drop-chance: 100

# Chance in percent to add enchantments to random dropped items
enchant-chance: 30

# Maximum number of random enchantments to add
max-enchants: 3

# Enable dropping enchanted books
allow-enchanted-books: true

# Chance to drop enchanted books
enchanted-book-chance: 10

# List of materials to exclude
unwanted-items:
  - AIR
  - CAVE_AIR
  - VOID_AIR
  - BEDROCK
  - BARRIER
  - COMMAND_BLOCK
  - COMMAND_BLOCK_MINECART
  - STRUCTURE_BLOCK
  - STRUCTURE_VOID
  - JIGSAW
  - DEBUG_STICK
  - LIGHT
  - REPEATING_COMMAND_BLOCK
  - CHAIN_COMMAND_BLOCK
  - KNOWLEDGE_BOOK
  - PLAYER_HEAD
  - PLAYER_WALL_HEAD
  - END_PORTAL_FRAME
  - NETHER_PORTAL
  - END_GATEWAY
  - SPAWNER

messages:
  receive-drop:
    enabled: true
    text: "§aYou received a random drop!"
  receive-enchanted-drop:
    enabled: true
    text: "§bLucky! You got an enchanted item!"
  receive-enchanted-book:
    enabled: true
    text: "§dYou found a mysterious enchanted book!"